[input]
audio_alsa_source=default
audio_backend=pulseaudio
audio_enabled=false
audio_jack_connect_system_capture=true
audio_jack_connect_system_playback=false
audio_pulseaudio_source=rnnoise_source
glinject_auto_launch=false
glinject_channel=
glinject_command=
glinject_limit_fps=false
glinject_relax_permissions=false
glinject_working_directory=
video_area=screen
video_area_follow_fullscreen=false
video_area_screen=0
video_frame_rate=60
video_h=1080
video_record_cursor=true
video_scale=false
video_scaled_h=480
video_scaled_w=854
video_v4l2_device=/dev/video0
video_w=1920
video_x=0
video_y=0
