#!/bin/bash

lock="/tmp/light-toggle.lock"
PID=$(pgrep -f "/bin/bash\ $XDG_CONFIG_HOME/bspwm/hooks/b9k_media_detect.sh")
# on=00008c

if [[ -e $lock ]]; then
	exit
else
	touch "$lock"
	og=$(xbacklight -get)
	dunstctl close-all
	for i in {3..1}; do
		dunstify --replace=650 -i screensaver "Screensaver" "Turning off screen in $i"
		sleep 1
	done

	kill -STOP "$PID"
	dunstify -C 650
	dunstctl set-paused true
	xbacklight -set 0
	# msi-perkeyrgb -d

	while true; do
		sleep 1
		if [[ $(xprintidle) -lt 1000 ]]; then
			kill -CONT "$PID"
			dunstctl set-paused false
			dunstify --replace=650 -i screensaver "Screensaver" "Welcome back"
			xbacklight -time 400 -set "$og"
			# msi-perkeyrgb -s "$on"
			rm "$lock"
			exit
		fi
	done
fi
