#!/bin/bash

if [[ $(pidof pavucontrol) != "" ]]; then
  killall -9 pavucontrol dunst
  dunstify -t 5000 -u critical "Pavucontrol" "Closed Pavucontrol"
  pkill -9 -f "pavu-toggle"
  exit
else
  pavucontrol &
fi

# eval "$(xdotool search --shell pavucontrol)" && bspc node "${WINDOWS[0]}" --to-desktop focused
