keyconfig_version = (3, 1, 7)
keyconfig_data = \
[("3D View",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("view3d.cursor3d", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("transform.translate",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True},
     {"properties":
      [("cursor_transform", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("view3d.localview", {"type": 'NUMPAD_SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'MOUSESMARTZOOM', "value": 'ANY'}, None),
    ("view3d.localview_remove_from", {"type": 'M', "value": 'PRESS'}, None),
    ("view3d.rotate", {"type": 'MOUSEROTATE', "value": 'ANY'}, None),
    ("view3d.rotate", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("view3d.move", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "shift": True}, None),
    ("view3d.rotate", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view3d.move", {"type": 'TRACKPADPAN', "value": 'ANY', "shift": True}, None),
    ("view3d.zoom", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.dolly", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ],
      },
     ),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view3d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view3d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view3d.zoom",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELINMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELOUTMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.view_center_camera", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_lock", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("center", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_view_pie'),
       ],
      },
     ),
    ("view3d.navigate", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "shift": True}, None),
    ("view3d.navigate", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "shift": True}, None),
    ("view3d.view_camera", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_2', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_4', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_persportho", {"type": 'NUMPAD_5', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_6', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_8', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_6', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("angle", 3.1415927),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_7', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'NORTH', "alt": True},
     {"properties":
      [("type", 'TOP'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'SOUTH', "alt": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'EAST', "alt": True},
     {"properties":
      [("type", 'RIGHT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'WEST', "alt": True},
     {"properties":
      [("type", 'LEFT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_center_pick", {"type": 'BUTTON5MOUSE', "value": 'CLICK', "alt": True}, None),
    ("view3d.ndof_orbit_zoom", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view3d.ndof_orbit", {"type": 'NDOF_MOTION', "value": 'ANY', "ctrl": True}, None),
    ("view3d.ndof_pan", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True}, None),
    ("view3d.ndof_all", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CW', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BACK', "value": 'PRESS'},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_LEFT', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BOTTOM', "value": 'PRESS'},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("center", True),
       ("object", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("view3d.clip_border", {"type": 'B', "value": 'PRESS', "alt": True}, None),
    ("view3d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.camera_to_view", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.object_as_camera", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("object.transform_axis_target", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("transform.skin_resize", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_PT_snapping'),
       ("keep_open", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_snap_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_orientations_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Z', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_shading_pie'),
       ],
      },
     ),
    ("view3d.toggle_shading",
     {"type": 'Z', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'WIREFRAME'),
       ],
      },
     ),
    ("view3d.toggle_xray", {"type": 'Z', "value": 'PRESS', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_box'),
       ("cycle", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Clip Editor",
  {"space_type": 'CLIP_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("clip.view_pan", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("clip.view_pan", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "shift": True}, None),
    ("clip.view_pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("clip.view_zoom", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("clip.view_zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("clip.view_zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("clip.view_zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("clip.view_zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("clip.view_zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True}, None),
    ("clip.view_zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True}, None),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("ratio", 1.0),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.5),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.25),
       ],
      },
     ),
    ("clip.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.125),
       ],
      },
     ),
    ("clip.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("clip.view_all",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("fit_view", True),
       ],
      },
     ),
    ("clip.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("clip.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("clip.view_ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("clip.frame_jump",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("position", 'PATHSTART'),
       ],
      },
     ),
    ("clip.frame_jump",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("position", 'PATHEND'),
       ],
      },
     ),
    ("clip.frame_jump",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "alt": True, "repeat": True},
     {"properties":
      [("position", 'FAILEDPREV'),
       ],
      },
     ),
    ("clip.frame_jump",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "alt": True, "repeat": True},
     {"properties":
      [("position", 'PATHSTART'),
       ],
      },
     ),
    ("clip.change_frame", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("clip.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("clip.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("clip.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("clip.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("clip.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("clip.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("clip.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("clip.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'CLIP_MT_select_grouped'),
       ],
      },
     ),
    ("clip.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("clip.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("clip.add_marker_slide", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("clip.delete_marker", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("clip.delete_marker", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("clip.slide_marker", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("clip.disable_markers",
     {"type": 'D', "value": 'PRESS', "shift": True},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("clip.delete_track", {"type": 'X', "value": 'PRESS'}, None),
    ("clip.delete_track", {"type": 'DEL', "value": 'PRESS'}, None),
    ("clip.lock_tracks",
     {"type": 'L', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'LOCK'),
       ],
      },
     ),
    ("clip.lock_tracks",
     {"type": 'L', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'UNLOCK'),
       ],
      },
     ),
    ("clip.hide_tracks_clear", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("clip.hide_tracks",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("clip.hide_tracks",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("clip.slide_plane_marker", {"type": 'LEFTMOUSE', "value": 'CLICK_DRAG'}, None),
    ("clip.keyframe_insert", {"type": 'I', "value": 'PRESS'}, None),
    ("clip.keyframe_delete", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("clip.join_tracks", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("clip.lock_selection_toggle", {"type": 'L', "value": 'PRESS'}, None),
    ("wm.context_toggle",
     {"type": 'D', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'space_data.show_disabled'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'space_data.show_marker_search'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.use_mute_footage'),
       ],
      },
     ),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("clip.clear_track_path",
     {"type": 'T', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'REMAINED'),
       ("clear_active", False),
       ],
      },
     ),
    ("clip.clear_track_path",
     {"type": 'T', "value": 'PRESS', "shift": True},
     {"properties":
      [("action", 'UPTO'),
       ("clear_active", False),
       ],
      },
     ),
    ("clip.clear_track_path",
     {"type": 'T', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("action", 'ALL'),
       ("clear_active", False),
       ],
      },
     ),
    ("clip.cursor_set", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("clip.copy_tracks", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("clip.paste_tracks", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'CLIP_MT_tracking_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'CLIP_MT_tracking_context_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'CLIP_MT_pivot_pie'),
       ],
      },
     ),
    ],
   },
  ),
 ("Gesture Box",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CANCEL", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("CANCEL", {"type": 'RIGHTMOUSE', "value": 'PRESS', "any": True}, None),
    ("SELECT", {"type": 'RIGHTMOUSE', "value": 'RELEASE', "any": True}, None),
    ("BEGIN", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("DESELECT", {"type": 'LEFTMOUSE', "value": 'RELEASE', "shift": True}, None),
    ("BEGIN", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("SELECT", {"type": 'LEFTMOUSE', "value": 'RELEASE', "any": True}, None),
    ("BEGIN", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("DESELECT", {"type": 'BUTTON5MOUSE', "value": 'RELEASE'}, None),
    ("MOVE", {"type": 'SPACE', "value": 'ANY', "any": True}, None),
    ],
   },
  ),
 ("Gesture Zoom Border",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CANCEL", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("CANCEL", {"type": 'RIGHTMOUSE', "value": 'ANY', "any": True}, None),
    ("BEGIN", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("IN", {"type": 'LEFTMOUSE', "value": 'RELEASE'}, None),
    ("BEGIN", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("OUT", {"type": 'BUTTON5MOUSE', "value": 'RELEASE'}, None),
    ],
   },
  ),
 ("Image",
  {"space_type": 'IMAGE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("image.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("image.view_all",
     {"type": 'HOME', "value": 'PRESS', "shift": True},
     {"properties":
      [("fit_view", True),
       ],
      },
     ),
    ("image.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("image.view_cursor_center", {"type": 'C', "value": 'PRESS', "shift": True}, None),
    ("image.view_pan", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("image.view_pan", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "shift": True}, None),
    ("image.view_pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("image.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("image.view_ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("image.view_zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True}, None),
    ("image.view_zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True}, None),
    ("image.view_zoom", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("image.view_zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("image.view_zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("image.view_zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("ratio", 1.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.5),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.25),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.125),
       ],
      },
     ),
    ("image.change_frame", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("image.sample", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("image.curves_point_set",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("point", 'BLACK_POINT'),
       ],
      },
     ),
    ("image.curves_point_set",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("point", 'WHITE_POINT'),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("mode", 'EDIT'),
       ("toggle", True),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 0),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 1),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 2),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 3),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FIVE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 4),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SIX', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 5),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SEVEN', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 6),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'EIGHT', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 7),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'NINE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 8),
       ],
      },
     ),
    ("image.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("image.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_mask_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_mask_context_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_pivot_pie'),
       ],
      },
     ),
    ],
   },
  ),
 ("Knife Tool Modal Map",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CANCEL", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("PANNING", {"type": 'BUTTON5MOUSE', "value": 'ANY'}, None),
    ("ADD_CUT_CLOSED", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK', "any": True}, None),
    ("ADD_CUT", {"type": 'LEFTMOUSE', "value": 'ANY', "any": True}, None),
    ("UNDO", {"type": 'Z', "value": 'PRESS', "ctrl": True}, None),
    ("CONFIRM", {"type": 'RET', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'SPACE', "value": 'PRESS', "any": True}, None),
    ("NEW_CUT", {"type": 'RIGHTMOUSE', "value": 'PRESS'}, None),
    ("SNAP_MIDPOINTS_ON", {"type": 'LEFT_SHIFT', "value": 'PRESS', "any": True}, None),
    ("SNAP_MIDPOINTS_OFF", {"type": 'LEFT_SHIFT', "value": 'RELEASE', "any": True}, None),
    ("SNAP_MIDPOINTS_ON", {"type": 'RIGHT_SHIFT', "value": 'PRESS', "any": True}, None),
    ("SNAP_MIDPOINTS_OFF", {"type": 'RIGHT_SHIFT', "value": 'RELEASE', "any": True}, None),
    ("IGNORE_SNAP_ON", {"type": 'LEFT_CTRL', "value": 'PRESS', "any": True}, None),
    ("IGNORE_SNAP_OFF", {"type": 'LEFT_CTRL', "value": 'RELEASE', "any": True}, None),
    ("IGNORE_SNAP_ON", {"type": 'RIGHT_CTRL', "value": 'PRESS', "any": True}, None),
    ("IGNORE_SNAP_OFF", {"type": 'RIGHT_CTRL', "value": 'RELEASE', "any": True}, None),
    ("X_AXIS", {"type": 'X', "value": 'PRESS'}, None),
    ("Y_AXIS", {"type": 'Y', "value": 'PRESS'}, None),
    ("Z_AXIS", {"type": 'Z', "value": 'PRESS'}, None),
    ("ANGLE_SNAP_TOGGLE", {"type": 'A', "value": 'PRESS'}, None),
    ("CYCLE_ANGLE_SNAP_EDGE", {"type": 'R', "value": 'PRESS'}, None),
    ("CUT_THROUGH_TOGGLE", {"type": 'C', "value": 'PRESS'}, None),
    ("SHOW_DISTANCE_ANGLE_TOGGLE", {"type": 'S', "value": 'PRESS'}, None),
    ("DEPTH_TEST_TOGGLE", {"type": 'V', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Node Editor",
  {"space_type": 'NODE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("node.select", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("node.select", {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("node.select", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select_box",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("tweak", True),
       ],
      },
     ),
    ("node.select_lasso",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("node.select_lasso",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("node.select_box",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("tweak", False),
       ],
      },
     ),
    ("node.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("node.link",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("detach", False),
       ],
      },
     ),
    ("node.link",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "ctrl": True},
     {"properties":
      [("detach", True),
       ],
      },
     ),
    ("node.resize", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("node.add_reroute", {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True}, None),
    ("node.links_cut", {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True}, None),
    ("node.links_mute", {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True, "alt": True}, None),
    ("node.select_link_viewer", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.backimage_move", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "alt": True}, None),
    ("node.backimage_zoom",
     {"type": 'V', "value": 'PRESS', "repeat": True},
     {"properties":
      [("factor", 0.8333333),
       ],
      },
     ),
    ("node.backimage_zoom",
     {"type": 'V', "value": 'PRESS', "alt": True, "repeat": True},
     {"properties":
      [("factor", 1.2),
       ],
      },
     ),
    ("node.backimage_fit", {"type": 'HOME', "value": 'PRESS', "alt": True}, None),
    ("node.backimage_sample", {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True}, None),
    ("node.link_make",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ],
      },
     ),
    ("node.link_make",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_add'),
       ],
      },
     ),
    ("node.duplicate_move",
     {"type": 'D', "value": 'PRESS', "shift": True},
     {"properties":
      [("NODE_OT_translate_attach",
        [("TRANSFORM_OT_translate",
          [("view2d_edge_pan", True),
           ],
          ),
         ],
        ),
       ],
      },
     ),
    ("node.duplicate_move_keep_inputs",
     {"type": 'D', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("NODE_OT_translate_attach",
        [("TRANSFORM_OT_translate",
          [("view2d_edge_pan", True),
           ],
          ),
         ],
        ),
       ],
      },
     ),
    ("node.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("node.detach", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("node.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("node.hide_toggle", {"type": 'H', "value": 'PRESS'}, None),
    ("node.mute_toggle", {"type": 'M', "value": 'PRESS'}, None),
    ("node.preview_toggle", {"type": 'H', "value": 'PRESS', "shift": True}, None),
    ("node.hide_socket_toggle", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("node.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("node.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("node.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_view_pie'),
       ],
      },
     ),
    ("node.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("node.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("node.delete_reconnect", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("node.delete_reconnect", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("node.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("node.select_linked_to", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("node.select_linked_from", {"type": 'L', "value": 'PRESS'}, None),
    ("node.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("node.select_grouped",
     {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select_same_type_step",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("prev", False),
       ],
      },
     ),
    ("node.select_same_type_step",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("prev", True),
       ],
      },
     ),
    ("node.find_node", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("node.group_make", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("node.group_ungroup", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("node.group_separate", {"type": 'P', "value": 'PRESS'}, None),
    ("node.group_edit",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("exit", False),
       ],
      },
     ),
    ("node.group_edit",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("exit", True),
       ],
      },
     ),
    ("node.read_viewlayers", {"type": 'R', "value": 'PRESS', "ctrl": True}, None),
    ("node.render_changed", {"type": 'Z', "value": 'PRESS'}, None),
    ("node.clipboard_copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("node.clipboard_paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("node.viewer_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("node.clear_viewer_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("node.translate_attach",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("view2d_edge_pan", True),
         ],
        ),
       ],
      },
     ),
    ("node.translate_attach",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("view2d_edge_pan", True),
         ],
        ),
       ],
      },
     ),
    ("node.translate_attach",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("view2d_edge_pan", True),
         ],
        ),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("view2d_edge_pan", True),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("view2d_edge_pan", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'EVT_TWEAK_L', "value": 'ANY'},
     {"properties":
      [("view2d_edge_pan", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("node.move_detach_links",
     {"type": 'D', "value": 'PRESS', "alt": True},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("view2d_edge_pan", True),
         ],
        ),
       ],
      },
     ),
    ("node.move_detach_links_release",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "alt": True},
     {"properties":
      [("NODE_OT_translate_attach",
        [("TRANSFORM_OT_translate",
          [("view2d_edge_pan", True),
           ],
          ),
         ],
        ),
       ],
      },
     ),
    ("node.move_detach_links",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "alt": True},
     {"properties":
      [("TRANSFORM_OT_translate",
        [("view2d_edge_pan", True),
         ],
        ),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("data_path", 'tool_settings.snap_node_element'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'NODE_MT_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Text",
  {"space_type": 'TEXT_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("wm.context_cycle_int",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.font_size'),
       ("reverse", False),
       ],
      },
     ),
    ("wm.context_cycle_int",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.font_size'),
       ("reverse", True),
       ],
      },
     ),
    ("wm.context_cycle_int",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("data_path", 'space_data.font_size'),
       ("reverse", False),
       ],
      },
     ),
    ("wm.context_cycle_int",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("data_path", 'space_data.font_size'),
       ("reverse", True),
       ],
      },
     ),
    ("text.new", {"type": 'N', "value": 'PRESS', "alt": True}, None),
    ("text.open", {"type": 'O', "value": 'PRESS', "alt": True}, None),
    ("text.reload", {"type": 'R', "value": 'PRESS', "alt": True}, None),
    ("text.save", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("text.save_as", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("text.run_script", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("text.cut", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("text.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("text.paste", {"type": 'V', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("text.cut", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("text.copy", {"type": 'INSERT', "value": 'PRESS', "ctrl": True}, None),
    ("text.paste", {"type": 'INSERT', "value": 'PRESS', "shift": True, "repeat": True}, None),
    ("text.duplicate_line", {"type": 'D', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("text.select_all", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("text.select_line", {"type": 'A', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("text.select_word", {"type": 'LEFTMOUSE', "value": 'DOUBLE_CLICK'}, None),
    ("text.move_lines",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("direction", 'UP'),
       ],
      },
     ),
    ("text.move_lines",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("direction", 'DOWN'),
       ],
      },
     ),
    ("text.indent_or_autocomplete", {"type": 'TAB', "value": 'PRESS', "repeat": True}, None),
    ("text.unindent", {"type": 'TAB', "value": 'PRESS', "shift": True, "repeat": True}, None),
    ("text.comment_toggle", {"type": 'SLASH', "value": 'PRESS', "ctrl": True}, None),
    ("text.move",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("type", 'LINE_BEGIN'),
       ],
      },
     ),
    ("text.move",
     {"type": 'END', "value": 'PRESS'},
     {"properties":
      [("type", 'LINE_END'),
       ],
      },
     ),
    ("text.move",
     {"type": 'E', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'LINE_END'),
       ],
      },
     ),
    ("text.move",
     {"type": 'E', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'LINE_END'),
       ],
      },
     ),
    ("text.move",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_CHARACTER'),
       ],
      },
     ),
    ("text.move",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'NEXT_CHARACTER'),
       ],
      },
     ),
    ("text.move",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_WORD'),
       ],
      },
     ),
    ("text.move",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'NEXT_WORD'),
       ],
      },
     ),
    ("text.move",
     {"type": 'UP_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_LINE'),
       ],
      },
     ),
    ("text.move",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'NEXT_LINE'),
       ],
      },
     ),
    ("text.move",
     {"type": 'PAGE_UP', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_PAGE'),
       ],
      },
     ),
    ("text.move",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'NEXT_PAGE'),
       ],
      },
     ),
    ("text.move",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'FILE_TOP'),
       ],
      },
     ),
    ("text.move",
     {"type": 'END', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'FILE_BOTTOM'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'HOME', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'LINE_BEGIN'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'END', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'LINE_END'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_CHARACTER'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'NEXT_CHARACTER'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_WORD'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'NEXT_WORD'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'UP_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_LINE'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'NEXT_LINE'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'PAGE_UP', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_PAGE'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'NEXT_PAGE'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'HOME', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'FILE_TOP'),
       ],
      },
     ),
    ("text.move_select",
     {"type": 'END', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'FILE_BOTTOM'),
       ],
      },
     ),
    ("text.delete",
     {"type": 'DEL', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'NEXT_CHARACTER'),
       ],
      },
     ),
    ("text.delete",
     {"type": 'BACK_SPACE', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_CHARACTER'),
       ],
      },
     ),
    ("text.delete",
     {"type": 'BACK_SPACE', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_CHARACTER'),
       ],
      },
     ),
    ("text.delete",
     {"type": 'DEL', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'NEXT_WORD'),
       ],
      },
     ),
    ("text.delete",
     {"type": 'BACK_SPACE', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PREVIOUS_WORD'),
       ],
      },
     ),
    ("text.overwrite_toggle", {"type": 'INSERT', "value": 'PRESS'}, None),
    ("text.scroll_bar", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("text.scroll_bar", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("text.scroll", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("text.scroll", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("text.selection_set", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("text.cursor_set", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("text.selection_set", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("text.scroll",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS'},
     {"properties":
      [("lines", -1),
       ],
      },
     ),
    ("text.scroll",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'},
     {"properties":
      [("lines", 1),
       ],
      },
     ),
    ("text.line_break", {"type": 'RET', "value": 'PRESS', "repeat": True}, None),
    ("text.line_break", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "repeat": True}, None),
    ("text.line_number", {"type": 'TEXTINPUT', "value": 'ANY', "any": True, "repeat": True}, None),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'TEXT_MT_context_menu'),
       ],
      },
     ),
    ("text.insert", {"type": 'TEXTINPUT', "value": 'ANY', "any": True, "repeat": True}, None),
    ],
   },
  ),
 ("Transform Modal Map",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CONFIRM", {"type": 'LEFTMOUSE', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'RET', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'SPACE', "value": 'PRESS', "any": True}, None),
    ("CANCEL", {"type": 'RIGHTMOUSE', "value": 'PRESS', "any": True}, None),
    ("CANCEL", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("AXIS_X", {"type": 'X', "value": 'PRESS'}, None),
    ("AXIS_Y", {"type": 'Y', "value": 'PRESS'}, None),
    ("AXIS_Z", {"type": 'Z', "value": 'PRESS'}, None),
    ("PLANE_X", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("PLANE_Y", {"type": 'Y', "value": 'PRESS', "shift": True}, None),
    ("PLANE_Z", {"type": 'Z', "value": 'PRESS', "shift": True}, None),
    ("CONS_OFF", {"type": 'C', "value": 'PRESS'}, None),
    ("TRANSLATE", {"type": 'G', "value": 'PRESS'}, None),
    ("ROTATE", {"type": 'R', "value": 'PRESS'}, None),
    ("RESIZE", {"type": 'S', "value": 'PRESS'}, None),
    ("SNAP_TOGGLE", {"type": 'TAB', "value": 'PRESS', "shift": True}, None),
    ("SNAP_INV_ON", {"type": 'LEFT_CTRL', "value": 'PRESS', "any": True}, None),
    ("SNAP_INV_OFF", {"type": 'LEFT_CTRL', "value": 'RELEASE', "any": True}, None),
    ("SNAP_INV_ON", {"type": 'RIGHT_CTRL', "value": 'PRESS', "any": True}, None),
    ("SNAP_INV_OFF", {"type": 'RIGHT_CTRL', "value": 'RELEASE', "any": True}, None),
    ("ADD_SNAP", {"type": 'A', "value": 'PRESS'}, None),
    ("ADD_SNAP", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("REMOVE_SNAP", {"type": 'A', "value": 'PRESS', "alt": True}, None),
    ("PROPORTIONAL_SIZE_UP", {"type": 'PAGE_UP', "value": 'PRESS', "repeat": True}, None),
    ("PROPORTIONAL_SIZE_DOWN", {"type": 'PAGE_DOWN', "value": 'PRESS', "repeat": True}, None),
    ("PROPORTIONAL_SIZE_UP", {"type": 'PAGE_UP', "value": 'PRESS', "shift": True, "repeat": True}, None),
    ("PROPORTIONAL_SIZE_DOWN", {"type": 'PAGE_DOWN', "value": 'PRESS', "shift": True, "repeat": True}, None),
    ("PROPORTIONAL_SIZE_UP", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("PROPORTIONAL_SIZE_DOWN", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("PROPORTIONAL_SIZE_UP", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "shift": True}, None),
    ("PROPORTIONAL_SIZE_DOWN", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "shift": True}, None),
    ("PROPORTIONAL_SIZE", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("EDGESLIDE_EDGE_NEXT", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "alt": True}, None),
    ("EDGESLIDE_PREV_NEXT", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "alt": True}, None),
    ("AUTOIK_CHAIN_LEN_UP", {"type": 'PAGE_UP', "value": 'PRESS', "repeat": True}, None),
    ("AUTOIK_CHAIN_LEN_DOWN", {"type": 'PAGE_DOWN', "value": 'PRESS', "repeat": True}, None),
    ("AUTOIK_CHAIN_LEN_UP", {"type": 'PAGE_UP', "value": 'PRESS', "shift": True, "repeat": True}, None),
    ("AUTOIK_CHAIN_LEN_DOWN", {"type": 'PAGE_DOWN', "value": 'PRESS', "shift": True, "repeat": True}, None),
    ("AUTOIK_CHAIN_LEN_UP", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("AUTOIK_CHAIN_LEN_DOWN", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("AUTOIK_CHAIN_LEN_UP", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "shift": True}, None),
    ("AUTOIK_CHAIN_LEN_DOWN", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "shift": True}, None),
    ("INSERTOFS_TOGGLE_DIR", {"type": 'T', "value": 'PRESS'}, None),
    ("AUTOCONSTRAIN", {"type": 'BUTTON5MOUSE', "value": 'ANY'}, None),
    ("AUTOCONSTRAINPLANE", {"type": 'BUTTON5MOUSE', "value": 'ANY', "shift": True}, None),
    ("PRECISION", {"type": 'LEFT_SHIFT', "value": 'ANY', "any": True}, None),
    ("PRECISION", {"type": 'RIGHT_SHIFT', "value": 'ANY', "any": True}, None),
    ],
   },
  ),
 ("View2D",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("view2d.scroller_activate", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroller_activate", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("view2d.pan", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("view2d.pan", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "shift": True}, None),
    ("view2d.pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view2d.scroll_right", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.scroll_left", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.scroll_down", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view2d.scroll_up", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view2d.ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view2d.zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("view2d.zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("view2d.zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True}, None),
    ("view2d.zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True}, None),
    ("view2d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view2d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view2d.scroll_down", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_up", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_right", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_left", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("view2d.zoom", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view2d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("View2D Buttons List",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("view2d.scroller_activate", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroller_activate", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("view2d.pan", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("view2d.pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view2d.scroll_down", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_up", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_down",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "repeat": True},
     {"properties":
      [("page", True),
       ],
      },
     ),
    ("view2d.scroll_up",
     {"type": 'PAGE_UP', "value": 'PRESS', "repeat": True},
     {"properties":
      [("page", True),
       ],
      },
     ),
    ("view2d.zoom", {"type": 'BUTTON5MOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view2d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view2d.zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True}, None),
    ("view2d.zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True}, None),
    ("view2d.reset", {"type": 'HOME', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("View3D Dolly Modal",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CONFIRM", {"type": 'BUTTON5MOUSE', "value": 'RELEASE'}, None),
    ("CONFIRM", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ],
   },
  ),
 ("View3D Fly Modal",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CANCEL", {"type": 'RIGHTMOUSE', "value": 'ANY', "any": True}, None),
    ("CANCEL", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'LEFTMOUSE', "value": 'ANY', "any": True}, None),
    ("CONFIRM", {"type": 'RET', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'SPACE', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "any": True}, None),
    ("ACCELERATE", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "any": True, "repeat": True}, None),
    ("DECELERATE", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "any": True, "repeat": True}, None),
    ("ACCELERATE", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "any": True}, None),
    ("DECELERATE", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("PAN_ENABLE", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("PAN_DISABLE", {"type": 'BUTTON5MOUSE', "value": 'RELEASE'}, None),
    ("FORWARD", {"type": 'W', "value": 'PRESS', "repeat": True}, None),
    ("BACKWARD", {"type": 'S', "value": 'PRESS', "repeat": True}, None),
    ("LEFT", {"type": 'A', "value": 'PRESS', "repeat": True}, None),
    ("RIGHT", {"type": 'D', "value": 'PRESS', "repeat": True}, None),
    ("UP", {"type": 'E', "value": 'PRESS', "repeat": True}, None),
    ("DOWN", {"type": 'Q', "value": 'PRESS', "repeat": True}, None),
    ("UP", {"type": 'R', "value": 'PRESS', "repeat": True}, None),
    ("DOWN", {"type": 'F', "value": 'PRESS', "repeat": True}, None),
    ("FORWARD", {"type": 'UP_ARROW', "value": 'PRESS', "repeat": True}, None),
    ("BACKWARD", {"type": 'DOWN_ARROW', "value": 'PRESS', "repeat": True}, None),
    ("LEFT", {"type": 'LEFT_ARROW', "value": 'PRESS', "repeat": True}, None),
    ("RIGHT", {"type": 'RIGHT_ARROW', "value": 'PRESS', "repeat": True}, None),
    ("AXIS_LOCK_X", {"type": 'X', "value": 'PRESS'}, None),
    ("AXIS_LOCK_Z", {"type": 'Z', "value": 'PRESS'}, None),
    ("PRECISION_ENABLE", {"type": 'LEFT_ALT', "value": 'PRESS', "any": True}, None),
    ("PRECISION_DISABLE", {"type": 'LEFT_ALT', "value": 'RELEASE', "any": True}, None),
    ("PRECISION_ENABLE", {"type": 'LEFT_SHIFT', "value": 'PRESS', "any": True}, None),
    ("PRECISION_DISABLE", {"type": 'LEFT_SHIFT', "value": 'RELEASE', "any": True}, None),
    ("FREELOOK_ENABLE", {"type": 'LEFT_CTRL', "value": 'PRESS', "any": True}, None),
    ("FREELOOK_DISABLE", {"type": 'LEFT_CTRL', "value": 'RELEASE', "any": True}, None),
    ],
   },
  ),
 ("View3D Gesture Circle",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CANCEL", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("CANCEL", {"type": 'RIGHTMOUSE', "value": 'ANY', "any": True}, None),
    ("CONFIRM", {"type": 'RET', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'NUMPAD_ENTER', "value": 'PRESS'}, None),
    ("SELECT", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("DESELECT", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("NOP", {"type": 'LEFTMOUSE', "value": 'RELEASE', "any": True}, None),
    ("DESELECT", {"type": 'BUTTON5MOUSE', "value": 'PRESS'}, None),
    ("NOP", {"type": 'BUTTON5MOUSE', "value": 'RELEASE'}, None),
    ("SUBTRACT", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("SUBTRACT", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True}, None),
    ("ADD", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("ADD", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True}, None),
    ("SIZE", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ],
   },
  ),
 ("View3D Move Modal",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CONFIRM", {"type": 'BUTTON5MOUSE', "value": 'RELEASE'}, None),
    ("CONFIRM", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ],
   },
  ),
 ("View3D Rotate Modal",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CONFIRM", {"type": 'BUTTON5MOUSE', "value": 'RELEASE'}, None),
    ("CONFIRM", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("AXIS_SNAP_ENABLE", {"type": 'LEFT_ALT', "value": 'PRESS', "any": True}, None),
    ("AXIS_SNAP_DISABLE", {"type": 'LEFT_ALT', "value": 'RELEASE', "any": True}, None),
    ],
   },
  ),
 ("View3D Walk Modal",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CANCEL", {"type": 'RIGHTMOUSE', "value": 'ANY', "any": True}, None),
    ("CANCEL", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'LEFTMOUSE', "value": 'ANY', "any": True}, None),
    ("CONFIRM", {"type": 'RET', "value": 'PRESS', "any": True}, None),
    ("CONFIRM", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "any": True}, None),
    ("FAST_ENABLE", {"type": 'LEFT_SHIFT', "value": 'PRESS', "any": True}, None),
    ("FAST_DISABLE", {"type": 'LEFT_SHIFT', "value": 'RELEASE', "any": True}, None),
    ("SLOW_ENABLE", {"type": 'LEFT_ALT', "value": 'PRESS', "any": True}, None),
    ("SLOW_DISABLE", {"type": 'LEFT_ALT', "value": 'RELEASE', "any": True}, None),
    ("FORWARD", {"type": 'W', "value": 'PRESS', "any": True}, None),
    ("BACKWARD", {"type": 'S', "value": 'PRESS', "any": True}, None),
    ("LEFT", {"type": 'A', "value": 'PRESS', "any": True}, None),
    ("RIGHT", {"type": 'D', "value": 'PRESS', "any": True}, None),
    ("UP", {"type": 'E', "value": 'PRESS', "any": True}, None),
    ("DOWN", {"type": 'Q', "value": 'PRESS', "any": True}, None),
    ("FORWARD_STOP", {"type": 'W', "value": 'RELEASE', "any": True}, None),
    ("BACKWARD_STOP", {"type": 'S', "value": 'RELEASE', "any": True}, None),
    ("LEFT_STOP", {"type": 'A', "value": 'RELEASE', "any": True}, None),
    ("RIGHT_STOP", {"type": 'D', "value": 'RELEASE', "any": True}, None),
    ("UP_STOP", {"type": 'E', "value": 'RELEASE', "any": True}, None),
    ("DOWN_STOP", {"type": 'Q', "value": 'RELEASE', "any": True}, None),
    ("FORWARD", {"type": 'UP_ARROW', "value": 'PRESS'}, None),
    ("BACKWARD", {"type": 'DOWN_ARROW', "value": 'PRESS'}, None),
    ("LEFT", {"type": 'LEFT_ARROW', "value": 'PRESS'}, None),
    ("RIGHT", {"type": 'RIGHT_ARROW', "value": 'PRESS'}, None),
    ("FORWARD_STOP", {"type": 'UP_ARROW', "value": 'RELEASE', "any": True}, None),
    ("BACKWARD_STOP", {"type": 'DOWN_ARROW', "value": 'RELEASE', "any": True}, None),
    ("LEFT_STOP", {"type": 'LEFT_ARROW', "value": 'RELEASE', "any": True}, None),
    ("RIGHT_STOP", {"type": 'RIGHT_ARROW', "value": 'RELEASE', "any": True}, None),
    ("GRAVITY_TOGGLE", {"type": 'TAB', "value": 'PRESS'}, None),
    ("GRAVITY_TOGGLE", {"type": 'G', "value": 'PRESS'}, None),
    ("JUMP", {"type": 'V', "value": 'PRESS', "any": True}, None),
    ("JUMP_STOP", {"type": 'V', "value": 'RELEASE', "any": True}, None),
    ("TELEPORT", {"type": 'SPACE', "value": 'PRESS', "any": True}, None),
    ("TELEPORT", {"type": 'BUTTON5MOUSE', "value": 'ANY'}, None),
    ("ACCELERATE", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "any": True, "repeat": True}, None),
    ("DECELERATE", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "any": True, "repeat": True}, None),
    ("ACCELERATE", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "any": True}, None),
    ("DECELERATE", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "any": True}, None),
    ("AXIS_LOCK_Z", {"type": 'Z', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("View3D Zoom Modal",
  {"space_type": 'EMPTY', "region_type": 'WINDOW', "modal": True},
  {"items":
   [("CONFIRM", {"type": 'BUTTON5MOUSE', "value": 'RELEASE'}, None),
    ("CONFIRM", {"type": 'ESC', "value": 'PRESS', "any": True}, None),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    # Only add keywords that are supported.
    from bpy.app import version as blender_version
    keywords = {}
    if blender_version >= (2, 92, 0):
        keywords["keyconfig_version"] = keyconfig_version
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(
        os.path.splitext(os.path.basename(__file__))[0],
        keyconfig_data,
        **keywords,
    )
