#!/bin/bash

#     __
#    / /_  _________ _      ______ ___
#   / __ \/ ___/ __ \ | /| / / __ `__ \
#  / /_/ (__  ) /_/ / |/ |/ / / / / / /
# /_.___/____/ .___/|__/|__/_/ /_/ /_/
#           /_/
#

# Restore wallpaper
nitrogen --restore &

# Starting SXHKD Keyboard Daemon
pgrep -x sxhkd >/dev/null || sxhkd &

# Launching polybar
bash "$HOME/.config/bspwm/polybar/launch.sh" &

# fix pointer
xsetroot -cursor_name left_ptr &

# Set configurations
for i in "$HOME"/.config/bspwm/configs/*.sh; do
	{
		eval "$i" &
	}
done

# Autostart
eval "$HOME/.config/bspwm/autostart.sh" &

# Set rules
for i in "$HOME"/.config/bspwm/rules/*.sh; do
	{
		eval "$i" &
	}
done

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager \
	eww copyq playerctld ksuperkey jgmenu \
	

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Enable power management
xfce4-power-manager &

# Start copyq
copyq --start-server &

# Start playerctld daemon to monitor playback
playerctld daemon &

# Start compositor
while pgrep -u "$UID" -x picom >/dev/null; do sleep 1; done
picom &

# Delete existing hooks and restart them
for i in "$HOME"/.config/bspwm/hooks/*.sh; do
	{
		pkill -9 -f "$i"
		eval "$i" &
	}
done

# Reached end of script
pkill -9 -f "dunst"
dunstify -i window_list "Successfully restarted BSPWM"
